_shared_step: &shared_step
  commands:
    - tools/ci/setup.sh
  plugins:
    - file:///buildkite/plugins/docker: &docker_plugin
        image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/node:current
        always-pull: true
        propagate-environment: true
        propagate-uid-gid: true
        volumes:
          # Allow git operations to work
          - ${HOME}/.ssh:/root/.ssh
          - ${HOME}/.git:/root/.git
        environment:
          - 'BUILDKITE_API_TOKEN'
    - file:///buildkite/plugins/cache: &cache_plugin
        key: yarn-node-modules-{{ checksum "yarn.lock" }}-v1
        paths:
          - ./.yarn/cache
          - ./.yarn/install-state.gz
  agents:
    queue: docker
    resource_class: large
  retry:
    automatic:
      limit: 1
  env:
    NODE_OPTIONS: --max-old-space-size=8192

steps:
  - label: ":package: Build"
    <<: *shared_step
    commands:
      - tools/ci/setup.sh
      - make build

  - label: ":mag: Lint"
    <<: *shared_step
    commands:
      - tools/ci/setup.sh
      - make lint

  - label: ":test_tube: Unit Tests"
    <<: *shared_step
    commands:
      - tools/ci/setup.sh
      - make test-unit

  - label: ":shield: Security Audit"
    <<: *shared_step
    commands:
      - tools/ci/setup.sh
      - make audit
    soft_fail: true

  - wait: ~
    continue_on_failure: true

  - label: ":bar_chart: Build Summary"
    commands:
      - echo "All parallel builds completed"
